import { packMetadata } from "@/src/util/packMetadata";
import "./globals.css";
import { Metadata } from "next";

export const metadata: Metadata = packMetadata({
    title: "Next.js",
    description: "Generated by Next.js",
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
